script: rake ci
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode 

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode # broken :( to be fixed in jruby 1.7.5?!!!
    - rvm: jruby-head
    - rvm: rbx-19mode # deadlocks :(

notifications:
  irc: "irc.freenode.org#celluloid"
